/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClinicSlugRouteRouteImport } from './routes/_authenticated/$clinicSlug/route'
import { Route as AuthenticatedClinicSlugAppointmentsRouteImport } from './routes/_authenticated/$clinicSlug/appointments'
import { Route as AuthenticatedClinicSlugDashboardRouteImport } from './routes/_authenticated/$clinicSlug/dashboard'
import { Route as AuthenticatedClinicSlugDepartmentsRouteImport } from './routes/_authenticated/$clinicSlug/departments'
import { Route as AuthenticatedClinicSlugEmployeesRouteImport } from './routes/_authenticated/$clinicSlug/employees'
import { Route as AuthenticatedClinicSlugPatientsRouteImport } from './routes/_authenticated/$clinicSlug/patients'
import { Route as AuthenticatedClinicSlugPositionsRouteImport } from './routes/_authenticated/$clinicSlug/positions'
import { Route as AuthenticatedClinicSlugRoomsRouteImport } from './routes/_authenticated/$clinicSlug/rooms'
import { Route as AuthenticatedClinicSlugShiftsRouteImport } from './routes/_authenticated/$clinicSlug/shifts'
import { Route as AuthenticatedClinicSlugAdminDashboardRouteImport } from './routes/_authenticated/$clinicSlug/admin.dashboard'
import { Route as AuthenticatedClinicSlugAdminIssuesRouteImport } from './routes/_authenticated/$clinicSlug/admin.issues'
import { Route as AuthenticatedClinicSlugAppointmentsBookingRouteImport } from './routes/_authenticated/$clinicSlug/appointments.booking'
import { Route as AuthenticatedClinicSlugAppointmentsCalendarRouteImport } from './routes/_authenticated/$clinicSlug/appointments.calendar'
import { Route as AuthenticatedClinicSlugAttendanceAdjustmentsRouteImport } from './routes/_authenticated/$clinicSlug/attendance.adjustments'
import { Route as AuthenticatedClinicSlugAttendanceCheckinRouteImport } from './routes/_authenticated/$clinicSlug/attendance.checkin'
import { Route as AuthenticatedClinicSlugAttendanceDailyRouteImport } from './routes/_authenticated/$clinicSlug/attendance.daily'
import { Route as AuthenticatedClinicSlugAttendanceLogsRouteImport } from './routes/_authenticated/$clinicSlug/attendance.logs'
import { Route as AuthenticatedClinicSlugAttendanceManualRouteImport } from './routes/_authenticated/$clinicSlug/attendance.manual'
import { Route as AuthenticatedClinicSlugAttendanceMonthlyRouteImport } from './routes/_authenticated/$clinicSlug/attendance.monthly'
import { Route as AuthenticatedClinicSlugAttendanceOvertimeRouteImport } from './routes/_authenticated/$clinicSlug/attendance.overtime'
import { Route as AuthenticatedClinicSlugBiometricDevicesRouteImport } from './routes/_authenticated/$clinicSlug/biometric.devices'
import { Route as AuthenticatedClinicSlugDoctorDashboardRouteImport } from './routes/_authenticated/$clinicSlug/doctor.dashboard'
import { Route as AuthenticatedClinicSlugDoctorProfileRouteImport } from './routes/_authenticated/$clinicSlug/doctor.profile'
import { Route as AuthenticatedClinicSlugDoctorScheduleRouteImport } from './routes/_authenticated/$clinicSlug/doctor.schedule'
import { Route as AuthenticatedClinicSlugHrAssignmentsRouteImport } from './routes/_authenticated/$clinicSlug/hr.assignments'
import { Route as AuthenticatedClinicSlugHrPayrollRouteImport } from './routes/_authenticated/$clinicSlug/hr.payroll'
import { Route as AuthenticatedClinicSlugHrSalaryRouteImport } from './routes/_authenticated/$clinicSlug/hr.salary'
import { Route as AuthenticatedClinicSlugIssuesMyReportsRouteImport } from './routes/_authenticated/$clinicSlug/issues.my-reports'
import { Route as AuthenticatedClinicSlugIssuesReportRouteImport } from './routes/_authenticated/$clinicSlug/issues.report'
import { Route as AuthenticatedClinicSlugPatientProfileRouteImport } from './routes/_authenticated/$clinicSlug/patient.profile'
import { Route as AuthenticatedClinicSlugReportsAppointmentsRouteImport } from './routes/_authenticated/$clinicSlug/reports.appointments'
import { Route as AuthenticatedClinicSlugReportsAttendanceRouteImport } from './routes/_authenticated/$clinicSlug/reports.attendance'
import { Route as AuthenticatedClinicSlugReportsExportRouteImport } from './routes/_authenticated/$clinicSlug/reports.export'
import { Route as AuthenticatedClinicSlugStaffProfilesRouteImport } from './routes/_authenticated/$clinicSlug/staff.profiles'
import { Route as AuthenticatedClinicSlugSystemAgentRouteImport } from './routes/_authenticated/$clinicSlug/system.agent'
import { Route as AuthenticatedClinicSlugSystemAuditLogsRouteImport } from './routes/_authenticated/$clinicSlug/system.audit-logs'
import { Route as AuthenticatedClinicSlugSystemClinicProfileRouteImport } from './routes/_authenticated/$clinicSlug/system.clinic-profile'
import { Route as AuthenticatedClinicSlugSystemDevicesRouteImport } from './routes/_authenticated/$clinicSlug/system.devices'
import { Route as AuthenticatedClinicSlugSystemGuideRouteImport } from './routes/_authenticated/$clinicSlug/system.guide'
import { Route as AuthenticatedClinicSlugSystemSettingsRouteImport } from './routes/_authenticated/$clinicSlug/system.settings'
import { Route as AuthenticatedClinicSlugSystemSyncRouteImport } from './routes/_authenticated/$clinicSlug/system.sync'
import { Route as AuthenticatedClinicSlugSystemUsersRouteImport } from './routes/_authenticated/$clinicSlug/system.users'
import { Route as ApiPublicDeviceEventsRouteImport } from './routes/api/public/device/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicSlugRouteRoute =
  AuthenticatedClinicSlugRouteRouteImport.update({
    id: '/$clinicSlug',
    path: '/$clinicSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicSlugAppointmentsRoute =
  AuthenticatedClinicSlugAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugDashboardRoute =
  AuthenticatedClinicSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugDepartmentsRoute =
  AuthenticatedClinicSlugDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugEmployeesRoute =
  AuthenticatedClinicSlugEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugPatientsRoute =
  AuthenticatedClinicSlugPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugPositionsRoute =
  AuthenticatedClinicSlugPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugRoomsRoute =
  AuthenticatedClinicSlugRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugShiftsRoute =
  AuthenticatedClinicSlugShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAdminDashboardRoute =
  AuthenticatedClinicSlugAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAdminIssuesRoute =
  AuthenticatedClinicSlugAdminIssuesRouteImport.update({
    id: '/admin/issues',
    path: '/admin/issues',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAppointmentsBookingRoute =
  AuthenticatedClinicSlugAppointmentsBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedClinicSlugAppointmentsRoute,
  } as any)
const AuthenticatedClinicSlugAppointmentsCalendarRoute =
  AuthenticatedClinicSlugAppointmentsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedClinicSlugAppointmentsRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceAdjustmentsRoute =
  AuthenticatedClinicSlugAttendanceAdjustmentsRouteImport.update({
    id: '/attendance/adjustments',
    path: '/attendance/adjustments',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceCheckinRoute =
  AuthenticatedClinicSlugAttendanceCheckinRouteImport.update({
    id: '/attendance/checkin',
    path: '/attendance/checkin',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceDailyRoute =
  AuthenticatedClinicSlugAttendanceDailyRouteImport.update({
    id: '/attendance/daily',
    path: '/attendance/daily',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceLogsRoute =
  AuthenticatedClinicSlugAttendanceLogsRouteImport.update({
    id: '/attendance/logs',
    path: '/attendance/logs',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceManualRoute =
  AuthenticatedClinicSlugAttendanceManualRouteImport.update({
    id: '/attendance/manual',
    path: '/attendance/manual',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceMonthlyRoute =
  AuthenticatedClinicSlugAttendanceMonthlyRouteImport.update({
    id: '/attendance/monthly',
    path: '/attendance/monthly',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugAttendanceOvertimeRoute =
  AuthenticatedClinicSlugAttendanceOvertimeRouteImport.update({
    id: '/attendance/overtime',
    path: '/attendance/overtime',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugBiometricDevicesRoute =
  AuthenticatedClinicSlugBiometricDevicesRouteImport.update({
    id: '/biometric/devices',
    path: '/biometric/devices',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugDoctorDashboardRoute =
  AuthenticatedClinicSlugDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugDoctorProfileRoute =
  AuthenticatedClinicSlugDoctorProfileRouteImport.update({
    id: '/doctor/profile',
    path: '/doctor/profile',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugDoctorScheduleRoute =
  AuthenticatedClinicSlugDoctorScheduleRouteImport.update({
    id: '/doctor/schedule',
    path: '/doctor/schedule',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugHrAssignmentsRoute =
  AuthenticatedClinicSlugHrAssignmentsRouteImport.update({
    id: '/hr/assignments',
    path: '/hr/assignments',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugHrPayrollRoute =
  AuthenticatedClinicSlugHrPayrollRouteImport.update({
    id: '/hr/payroll',
    path: '/hr/payroll',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugHrSalaryRoute =
  AuthenticatedClinicSlugHrSalaryRouteImport.update({
    id: '/hr/salary',
    path: '/hr/salary',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugIssuesMyReportsRoute =
  AuthenticatedClinicSlugIssuesMyReportsRouteImport.update({
    id: '/issues/my-reports',
    path: '/issues/my-reports',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugIssuesReportRoute =
  AuthenticatedClinicSlugIssuesReportRouteImport.update({
    id: '/issues/report',
    path: '/issues/report',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugPatientProfileRoute =
  AuthenticatedClinicSlugPatientProfileRouteImport.update({
    id: '/patient/profile',
    path: '/patient/profile',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugReportsAppointmentsRoute =
  AuthenticatedClinicSlugReportsAppointmentsRouteImport.update({
    id: '/reports/appointments',
    path: '/reports/appointments',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugReportsAttendanceRoute =
  AuthenticatedClinicSlugReportsAttendanceRouteImport.update({
    id: '/reports/attendance',
    path: '/reports/attendance',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugReportsExportRoute =
  AuthenticatedClinicSlugReportsExportRouteImport.update({
    id: '/reports/export',
    path: '/reports/export',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugStaffProfilesRoute =
  AuthenticatedClinicSlugStaffProfilesRouteImport.update({
    id: '/staff/profiles',
    path: '/staff/profiles',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemAgentRoute =
  AuthenticatedClinicSlugSystemAgentRouteImport.update({
    id: '/system/agent',
    path: '/system/agent',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemAuditLogsRoute =
  AuthenticatedClinicSlugSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemClinicProfileRoute =
  AuthenticatedClinicSlugSystemClinicProfileRouteImport.update({
    id: '/system/clinic-profile',
    path: '/system/clinic-profile',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemDevicesRoute =
  AuthenticatedClinicSlugSystemDevicesRouteImport.update({
    id: '/system/devices',
    path: '/system/devices',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemGuideRoute =
  AuthenticatedClinicSlugSystemGuideRouteImport.update({
    id: '/system/guide',
    path: '/system/guide',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemSettingsRoute =
  AuthenticatedClinicSlugSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemSyncRoute =
  AuthenticatedClinicSlugSystemSyncRouteImport.update({
    id: '/system/sync',
    path: '/system/sync',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const AuthenticatedClinicSlugSystemUsersRoute =
  AuthenticatedClinicSlugSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedClinicSlugRouteRoute,
  } as any)
const ApiPublicDeviceEventsRoute = ApiPublicDeviceEventsRouteImport.update({
  id: '/api/public/device/events',
  path: '/api/public/device/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$clinicSlug': typeof AuthenticatedClinicSlugRouteRouteWithChildren
  '/$clinicSlug/appointments': typeof AuthenticatedClinicSlugAppointmentsRouteWithChildren
  '/$clinicSlug/dashboard': typeof AuthenticatedClinicSlugDashboardRoute
  '/$clinicSlug/departments': typeof AuthenticatedClinicSlugDepartmentsRoute
  '/$clinicSlug/employees': typeof AuthenticatedClinicSlugEmployeesRoute
  '/$clinicSlug/patients': typeof AuthenticatedClinicSlugPatientsRoute
  '/$clinicSlug/positions': typeof AuthenticatedClinicSlugPositionsRoute
  '/$clinicSlug/rooms': typeof AuthenticatedClinicSlugRoomsRoute
  '/$clinicSlug/shifts': typeof AuthenticatedClinicSlugShiftsRoute
  '/$clinicSlug/admin/dashboard': typeof AuthenticatedClinicSlugAdminDashboardRoute
  '/$clinicSlug/admin/issues': typeof AuthenticatedClinicSlugAdminIssuesRoute
  '/$clinicSlug/appointments/booking': typeof AuthenticatedClinicSlugAppointmentsBookingRoute
  '/$clinicSlug/appointments/calendar': typeof AuthenticatedClinicSlugAppointmentsCalendarRoute
  '/$clinicSlug/attendance/adjustments': typeof AuthenticatedClinicSlugAttendanceAdjustmentsRoute
  '/$clinicSlug/attendance/checkin': typeof AuthenticatedClinicSlugAttendanceCheckinRoute
  '/$clinicSlug/attendance/daily': typeof AuthenticatedClinicSlugAttendanceDailyRoute
  '/$clinicSlug/attendance/logs': typeof AuthenticatedClinicSlugAttendanceLogsRoute
  '/$clinicSlug/attendance/manual': typeof AuthenticatedClinicSlugAttendanceManualRoute
  '/$clinicSlug/attendance/monthly': typeof AuthenticatedClinicSlugAttendanceMonthlyRoute
  '/$clinicSlug/attendance/overtime': typeof AuthenticatedClinicSlugAttendanceOvertimeRoute
  '/$clinicSlug/biometric/devices': typeof AuthenticatedClinicSlugBiometricDevicesRoute
  '/$clinicSlug/doctor/dashboard': typeof AuthenticatedClinicSlugDoctorDashboardRoute
  '/$clinicSlug/doctor/profile': typeof AuthenticatedClinicSlugDoctorProfileRoute
  '/$clinicSlug/doctor/schedule': typeof AuthenticatedClinicSlugDoctorScheduleRoute
  '/$clinicSlug/hr/assignments': typeof AuthenticatedClinicSlugHrAssignmentsRoute
  '/$clinicSlug/hr/payroll': typeof AuthenticatedClinicSlugHrPayrollRoute
  '/$clinicSlug/hr/salary': typeof AuthenticatedClinicSlugHrSalaryRoute
  '/$clinicSlug/issues/my-reports': typeof AuthenticatedClinicSlugIssuesMyReportsRoute
  '/$clinicSlug/issues/report': typeof AuthenticatedClinicSlugIssuesReportRoute
  '/$clinicSlug/patient/profile': typeof AuthenticatedClinicSlugPatientProfileRoute
  '/$clinicSlug/reports/appointments': typeof AuthenticatedClinicSlugReportsAppointmentsRoute
  '/$clinicSlug/reports/attendance': typeof AuthenticatedClinicSlugReportsAttendanceRoute
  '/$clinicSlug/reports/export': typeof AuthenticatedClinicSlugReportsExportRoute
  '/$clinicSlug/staff/profiles': typeof AuthenticatedClinicSlugStaffProfilesRoute
  '/$clinicSlug/system/agent': typeof AuthenticatedClinicSlugSystemAgentRoute
  '/$clinicSlug/system/audit-logs': typeof AuthenticatedClinicSlugSystemAuditLogsRoute
  '/$clinicSlug/system/clinic-profile': typeof AuthenticatedClinicSlugSystemClinicProfileRoute
  '/$clinicSlug/system/devices': typeof AuthenticatedClinicSlugSystemDevicesRoute
  '/$clinicSlug/system/guide': typeof AuthenticatedClinicSlugSystemGuideRoute
  '/$clinicSlug/system/settings': typeof AuthenticatedClinicSlugSystemSettingsRoute
  '/$clinicSlug/system/sync': typeof AuthenticatedClinicSlugSystemSyncRoute
  '/$clinicSlug/system/users': typeof AuthenticatedClinicSlugSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$clinicSlug': typeof AuthenticatedClinicSlugRouteRouteWithChildren
  '/$clinicSlug/appointments': typeof AuthenticatedClinicSlugAppointmentsRouteWithChildren
  '/$clinicSlug/dashboard': typeof AuthenticatedClinicSlugDashboardRoute
  '/$clinicSlug/departments': typeof AuthenticatedClinicSlugDepartmentsRoute
  '/$clinicSlug/employees': typeof AuthenticatedClinicSlugEmployeesRoute
  '/$clinicSlug/patients': typeof AuthenticatedClinicSlugPatientsRoute
  '/$clinicSlug/positions': typeof AuthenticatedClinicSlugPositionsRoute
  '/$clinicSlug/rooms': typeof AuthenticatedClinicSlugRoomsRoute
  '/$clinicSlug/shifts': typeof AuthenticatedClinicSlugShiftsRoute
  '/$clinicSlug/admin/dashboard': typeof AuthenticatedClinicSlugAdminDashboardRoute
  '/$clinicSlug/admin/issues': typeof AuthenticatedClinicSlugAdminIssuesRoute
  '/$clinicSlug/appointments/booking': typeof AuthenticatedClinicSlugAppointmentsBookingRoute
  '/$clinicSlug/appointments/calendar': typeof AuthenticatedClinicSlugAppointmentsCalendarRoute
  '/$clinicSlug/attendance/adjustments': typeof AuthenticatedClinicSlugAttendanceAdjustmentsRoute
  '/$clinicSlug/attendance/checkin': typeof AuthenticatedClinicSlugAttendanceCheckinRoute
  '/$clinicSlug/attendance/daily': typeof AuthenticatedClinicSlugAttendanceDailyRoute
  '/$clinicSlug/attendance/logs': typeof AuthenticatedClinicSlugAttendanceLogsRoute
  '/$clinicSlug/attendance/manual': typeof AuthenticatedClinicSlugAttendanceManualRoute
  '/$clinicSlug/attendance/monthly': typeof AuthenticatedClinicSlugAttendanceMonthlyRoute
  '/$clinicSlug/attendance/overtime': typeof AuthenticatedClinicSlugAttendanceOvertimeRoute
  '/$clinicSlug/biometric/devices': typeof AuthenticatedClinicSlugBiometricDevicesRoute
  '/$clinicSlug/doctor/dashboard': typeof AuthenticatedClinicSlugDoctorDashboardRoute
  '/$clinicSlug/doctor/profile': typeof AuthenticatedClinicSlugDoctorProfileRoute
  '/$clinicSlug/doctor/schedule': typeof AuthenticatedClinicSlugDoctorScheduleRoute
  '/$clinicSlug/hr/assignments': typeof AuthenticatedClinicSlugHrAssignmentsRoute
  '/$clinicSlug/hr/payroll': typeof AuthenticatedClinicSlugHrPayrollRoute
  '/$clinicSlug/hr/salary': typeof AuthenticatedClinicSlugHrSalaryRoute
  '/$clinicSlug/issues/my-reports': typeof AuthenticatedClinicSlugIssuesMyReportsRoute
  '/$clinicSlug/issues/report': typeof AuthenticatedClinicSlugIssuesReportRoute
  '/$clinicSlug/patient/profile': typeof AuthenticatedClinicSlugPatientProfileRoute
  '/$clinicSlug/reports/appointments': typeof AuthenticatedClinicSlugReportsAppointmentsRoute
  '/$clinicSlug/reports/attendance': typeof AuthenticatedClinicSlugReportsAttendanceRoute
  '/$clinicSlug/reports/export': typeof AuthenticatedClinicSlugReportsExportRoute
  '/$clinicSlug/staff/profiles': typeof AuthenticatedClinicSlugStaffProfilesRoute
  '/$clinicSlug/system/agent': typeof AuthenticatedClinicSlugSystemAgentRoute
  '/$clinicSlug/system/audit-logs': typeof AuthenticatedClinicSlugSystemAuditLogsRoute
  '/$clinicSlug/system/clinic-profile': typeof AuthenticatedClinicSlugSystemClinicProfileRoute
  '/$clinicSlug/system/devices': typeof AuthenticatedClinicSlugSystemDevicesRoute
  '/$clinicSlug/system/guide': typeof AuthenticatedClinicSlugSystemGuideRoute
  '/$clinicSlug/system/settings': typeof AuthenticatedClinicSlugSystemSettingsRoute
  '/$clinicSlug/system/sync': typeof AuthenticatedClinicSlugSystemSyncRoute
  '/$clinicSlug/system/users': typeof AuthenticatedClinicSlugSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/$clinicSlug': typeof AuthenticatedClinicSlugRouteRouteWithChildren
  '/_authenticated/$clinicSlug/appointments': typeof AuthenticatedClinicSlugAppointmentsRouteWithChildren
  '/_authenticated/$clinicSlug/dashboard': typeof AuthenticatedClinicSlugDashboardRoute
  '/_authenticated/$clinicSlug/departments': typeof AuthenticatedClinicSlugDepartmentsRoute
  '/_authenticated/$clinicSlug/employees': typeof AuthenticatedClinicSlugEmployeesRoute
  '/_authenticated/$clinicSlug/patients': typeof AuthenticatedClinicSlugPatientsRoute
  '/_authenticated/$clinicSlug/positions': typeof AuthenticatedClinicSlugPositionsRoute
  '/_authenticated/$clinicSlug/rooms': typeof AuthenticatedClinicSlugRoomsRoute
  '/_authenticated/$clinicSlug/shifts': typeof AuthenticatedClinicSlugShiftsRoute
  '/_authenticated/$clinicSlug/admin/dashboard': typeof AuthenticatedClinicSlugAdminDashboardRoute
  '/_authenticated/$clinicSlug/admin/issues': typeof AuthenticatedClinicSlugAdminIssuesRoute
  '/_authenticated/$clinicSlug/appointments/booking': typeof AuthenticatedClinicSlugAppointmentsBookingRoute
  '/_authenticated/$clinicSlug/appointments/calendar': typeof AuthenticatedClinicSlugAppointmentsCalendarRoute
  '/_authenticated/$clinicSlug/attendance/adjustments': typeof AuthenticatedClinicSlugAttendanceAdjustmentsRoute
  '/_authenticated/$clinicSlug/attendance/checkin': typeof AuthenticatedClinicSlugAttendanceCheckinRoute
  '/_authenticated/$clinicSlug/attendance/daily': typeof AuthenticatedClinicSlugAttendanceDailyRoute
  '/_authenticated/$clinicSlug/attendance/logs': typeof AuthenticatedClinicSlugAttendanceLogsRoute
  '/_authenticated/$clinicSlug/attendance/manual': typeof AuthenticatedClinicSlugAttendanceManualRoute
  '/_authenticated/$clinicSlug/attendance/monthly': typeof AuthenticatedClinicSlugAttendanceMonthlyRoute
  '/_authenticated/$clinicSlug/attendance/overtime': typeof AuthenticatedClinicSlugAttendanceOvertimeRoute
  '/_authenticated/$clinicSlug/biometric/devices': typeof AuthenticatedClinicSlugBiometricDevicesRoute
  '/_authenticated/$clinicSlug/doctor/dashboard': typeof AuthenticatedClinicSlugDoctorDashboardRoute
  '/_authenticated/$clinicSlug/doctor/profile': typeof AuthenticatedClinicSlugDoctorProfileRoute
  '/_authenticated/$clinicSlug/doctor/schedule': typeof AuthenticatedClinicSlugDoctorScheduleRoute
  '/_authenticated/$clinicSlug/hr/assignments': typeof AuthenticatedClinicSlugHrAssignmentsRoute
  '/_authenticated/$clinicSlug/hr/payroll': typeof AuthenticatedClinicSlugHrPayrollRoute
  '/_authenticated/$clinicSlug/hr/salary': typeof AuthenticatedClinicSlugHrSalaryRoute
  '/_authenticated/$clinicSlug/issues/my-reports': typeof AuthenticatedClinicSlugIssuesMyReportsRoute
  '/_authenticated/$clinicSlug/issues/report': typeof AuthenticatedClinicSlugIssuesReportRoute
  '/_authenticated/$clinicSlug/patient/profile': typeof AuthenticatedClinicSlugPatientProfileRoute
  '/_authenticated/$clinicSlug/reports/appointments': typeof AuthenticatedClinicSlugReportsAppointmentsRoute
  '/_authenticated/$clinicSlug/reports/attendance': typeof AuthenticatedClinicSlugReportsAttendanceRoute
  '/_authenticated/$clinicSlug/reports/export': typeof AuthenticatedClinicSlugReportsExportRoute
  '/_authenticated/$clinicSlug/staff/profiles': typeof AuthenticatedClinicSlugStaffProfilesRoute
  '/_authenticated/$clinicSlug/system/agent': typeof AuthenticatedClinicSlugSystemAgentRoute
  '/_authenticated/$clinicSlug/system/audit-logs': typeof AuthenticatedClinicSlugSystemAuditLogsRoute
  '/_authenticated/$clinicSlug/system/clinic-profile': typeof AuthenticatedClinicSlugSystemClinicProfileRoute
  '/_authenticated/$clinicSlug/system/devices': typeof AuthenticatedClinicSlugSystemDevicesRoute
  '/_authenticated/$clinicSlug/system/guide': typeof AuthenticatedClinicSlugSystemGuideRoute
  '/_authenticated/$clinicSlug/system/settings': typeof AuthenticatedClinicSlugSystemSettingsRoute
  '/_authenticated/$clinicSlug/system/sync': typeof AuthenticatedClinicSlugSystemSyncRoute
  '/_authenticated/$clinicSlug/system/users': typeof AuthenticatedClinicSlugSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$clinicSlug'
    | '/$clinicSlug/appointments'
    | '/$clinicSlug/dashboard'
    | '/$clinicSlug/departments'
    | '/$clinicSlug/employees'
    | '/$clinicSlug/patients'
    | '/$clinicSlug/positions'
    | '/$clinicSlug/rooms'
    | '/$clinicSlug/shifts'
    | '/$clinicSlug/admin/dashboard'
    | '/$clinicSlug/admin/issues'
    | '/$clinicSlug/appointments/booking'
    | '/$clinicSlug/appointments/calendar'
    | '/$clinicSlug/attendance/adjustments'
    | '/$clinicSlug/attendance/checkin'
    | '/$clinicSlug/attendance/daily'
    | '/$clinicSlug/attendance/logs'
    | '/$clinicSlug/attendance/manual'
    | '/$clinicSlug/attendance/monthly'
    | '/$clinicSlug/attendance/overtime'
    | '/$clinicSlug/biometric/devices'
    | '/$clinicSlug/doctor/dashboard'
    | '/$clinicSlug/doctor/profile'
    | '/$clinicSlug/doctor/schedule'
    | '/$clinicSlug/hr/assignments'
    | '/$clinicSlug/hr/payroll'
    | '/$clinicSlug/hr/salary'
    | '/$clinicSlug/issues/my-reports'
    | '/$clinicSlug/issues/report'
    | '/$clinicSlug/patient/profile'
    | '/$clinicSlug/reports/appointments'
    | '/$clinicSlug/reports/attendance'
    | '/$clinicSlug/reports/export'
    | '/$clinicSlug/staff/profiles'
    | '/$clinicSlug/system/agent'
    | '/$clinicSlug/system/audit-logs'
    | '/$clinicSlug/system/clinic-profile'
    | '/$clinicSlug/system/devices'
    | '/$clinicSlug/system/guide'
    | '/$clinicSlug/system/settings'
    | '/$clinicSlug/system/sync'
    | '/$clinicSlug/system/users'
    | '/api/public/device/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$clinicSlug'
    | '/$clinicSlug/appointments'
    | '/$clinicSlug/dashboard'
    | '/$clinicSlug/departments'
    | '/$clinicSlug/employees'
    | '/$clinicSlug/patients'
    | '/$clinicSlug/positions'
    | '/$clinicSlug/rooms'
    | '/$clinicSlug/shifts'
    | '/$clinicSlug/admin/dashboard'
    | '/$clinicSlug/admin/issues'
    | '/$clinicSlug/appointments/booking'
    | '/$clinicSlug/appointments/calendar'
    | '/$clinicSlug/attendance/adjustments'
    | '/$clinicSlug/attendance/checkin'
    | '/$clinicSlug/attendance/daily'
    | '/$clinicSlug/attendance/logs'
    | '/$clinicSlug/attendance/manual'
    | '/$clinicSlug/attendance/monthly'
    | '/$clinicSlug/attendance/overtime'
    | '/$clinicSlug/biometric/devices'
    | '/$clinicSlug/doctor/dashboard'
    | '/$clinicSlug/doctor/profile'
    | '/$clinicSlug/doctor/schedule'
    | '/$clinicSlug/hr/assignments'
    | '/$clinicSlug/hr/payroll'
    | '/$clinicSlug/hr/salary'
    | '/$clinicSlug/issues/my-reports'
    | '/$clinicSlug/issues/report'
    | '/$clinicSlug/patient/profile'
    | '/$clinicSlug/reports/appointments'
    | '/$clinicSlug/reports/attendance'
    | '/$clinicSlug/reports/export'
    | '/$clinicSlug/staff/profiles'
    | '/$clinicSlug/system/agent'
    | '/$clinicSlug/system/audit-logs'
    | '/$clinicSlug/system/clinic-profile'
    | '/$clinicSlug/system/devices'
    | '/$clinicSlug/system/guide'
    | '/$clinicSlug/system/settings'
    | '/$clinicSlug/system/sync'
    | '/$clinicSlug/system/users'
    | '/api/public/device/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/$clinicSlug'
    | '/_authenticated/$clinicSlug/appointments'
    | '/_authenticated/$clinicSlug/dashboard'
    | '/_authenticated/$clinicSlug/departments'
    | '/_authenticated/$clinicSlug/employees'
    | '/_authenticated/$clinicSlug/patients'
    | '/_authenticated/$clinicSlug/positions'
    | '/_authenticated/$clinicSlug/rooms'
    | '/_authenticated/$clinicSlug/shifts'
    | '/_authenticated/$clinicSlug/admin/dashboard'
    | '/_authenticated/$clinicSlug/admin/issues'
    | '/_authenticated/$clinicSlug/appointments/booking'
    | '/_authenticated/$clinicSlug/appointments/calendar'
    | '/_authenticated/$clinicSlug/attendance/adjustments'
    | '/_authenticated/$clinicSlug/attendance/checkin'
    | '/_authenticated/$clinicSlug/attendance/daily'
    | '/_authenticated/$clinicSlug/attendance/logs'
    | '/_authenticated/$clinicSlug/attendance/manual'
    | '/_authenticated/$clinicSlug/attendance/monthly'
    | '/_authenticated/$clinicSlug/attendance/overtime'
    | '/_authenticated/$clinicSlug/biometric/devices'
    | '/_authenticated/$clinicSlug/doctor/dashboard'
    | '/_authenticated/$clinicSlug/doctor/profile'
    | '/_authenticated/$clinicSlug/doctor/schedule'
    | '/_authenticated/$clinicSlug/hr/assignments'
    | '/_authenticated/$clinicSlug/hr/payroll'
    | '/_authenticated/$clinicSlug/hr/salary'
    | '/_authenticated/$clinicSlug/issues/my-reports'
    | '/_authenticated/$clinicSlug/issues/report'
    | '/_authenticated/$clinicSlug/patient/profile'
    | '/_authenticated/$clinicSlug/reports/appointments'
    | '/_authenticated/$clinicSlug/reports/attendance'
    | '/_authenticated/$clinicSlug/reports/export'
    | '/_authenticated/$clinicSlug/staff/profiles'
    | '/_authenticated/$clinicSlug/system/agent'
    | '/_authenticated/$clinicSlug/system/audit-logs'
    | '/_authenticated/$clinicSlug/system/clinic-profile'
    | '/_authenticated/$clinicSlug/system/devices'
    | '/_authenticated/$clinicSlug/system/guide'
    | '/_authenticated/$clinicSlug/system/settings'
    | '/_authenticated/$clinicSlug/system/sync'
    | '/_authenticated/$clinicSlug/system/users'
    | '/api/public/device/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDeviceEventsRoute: typeof ApiPublicDeviceEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$clinicSlug': {
      id: '/_authenticated/$clinicSlug'
      path: '/$clinicSlug'
      fullPath: '/$clinicSlug'
      preLoaderRoute: typeof AuthenticatedClinicSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$clinicSlug/appointments': {
      id: '/_authenticated/$clinicSlug/appointments'
      path: '/appointments'
      fullPath: '/$clinicSlug/appointments'
      preLoaderRoute: typeof AuthenticatedClinicSlugAppointmentsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/dashboard': {
      id: '/_authenticated/$clinicSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$clinicSlug/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/departments': {
      id: '/_authenticated/$clinicSlug/departments'
      path: '/departments'
      fullPath: '/$clinicSlug/departments'
      preLoaderRoute: typeof AuthenticatedClinicSlugDepartmentsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/employees': {
      id: '/_authenticated/$clinicSlug/employees'
      path: '/employees'
      fullPath: '/$clinicSlug/employees'
      preLoaderRoute: typeof AuthenticatedClinicSlugEmployeesRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/patients': {
      id: '/_authenticated/$clinicSlug/patients'
      path: '/patients'
      fullPath: '/$clinicSlug/patients'
      preLoaderRoute: typeof AuthenticatedClinicSlugPatientsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/positions': {
      id: '/_authenticated/$clinicSlug/positions'
      path: '/positions'
      fullPath: '/$clinicSlug/positions'
      preLoaderRoute: typeof AuthenticatedClinicSlugPositionsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/rooms': {
      id: '/_authenticated/$clinicSlug/rooms'
      path: '/rooms'
      fullPath: '/$clinicSlug/rooms'
      preLoaderRoute: typeof AuthenticatedClinicSlugRoomsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/shifts': {
      id: '/_authenticated/$clinicSlug/shifts'
      path: '/shifts'
      fullPath: '/$clinicSlug/shifts'
      preLoaderRoute: typeof AuthenticatedClinicSlugShiftsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/admin/dashboard': {
      id: '/_authenticated/$clinicSlug/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/$clinicSlug/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicSlugAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/admin/issues': {
      id: '/_authenticated/$clinicSlug/admin/issues'
      path: '/admin/issues'
      fullPath: '/$clinicSlug/admin/issues'
      preLoaderRoute: typeof AuthenticatedClinicSlugAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/appointments/booking': {
      id: '/_authenticated/$clinicSlug/appointments/booking'
      path: '/booking'
      fullPath: '/$clinicSlug/appointments/booking'
      preLoaderRoute: typeof AuthenticatedClinicSlugAppointmentsBookingRouteImport
      parentRoute: typeof AuthenticatedClinicSlugAppointmentsRoute
    }
    '/_authenticated/$clinicSlug/appointments/calendar': {
      id: '/_authenticated/$clinicSlug/appointments/calendar'
      path: '/calendar'
      fullPath: '/$clinicSlug/appointments/calendar'
      preLoaderRoute: typeof AuthenticatedClinicSlugAppointmentsCalendarRouteImport
      parentRoute: typeof AuthenticatedClinicSlugAppointmentsRoute
    }
    '/_authenticated/$clinicSlug/attendance/adjustments': {
      id: '/_authenticated/$clinicSlug/attendance/adjustments'
      path: '/attendance/adjustments'
      fullPath: '/$clinicSlug/attendance/adjustments'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/checkin': {
      id: '/_authenticated/$clinicSlug/attendance/checkin'
      path: '/attendance/checkin'
      fullPath: '/$clinicSlug/attendance/checkin'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceCheckinRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/daily': {
      id: '/_authenticated/$clinicSlug/attendance/daily'
      path: '/attendance/daily'
      fullPath: '/$clinicSlug/attendance/daily'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceDailyRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/logs': {
      id: '/_authenticated/$clinicSlug/attendance/logs'
      path: '/attendance/logs'
      fullPath: '/$clinicSlug/attendance/logs'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceLogsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/manual': {
      id: '/_authenticated/$clinicSlug/attendance/manual'
      path: '/attendance/manual'
      fullPath: '/$clinicSlug/attendance/manual'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceManualRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/monthly': {
      id: '/_authenticated/$clinicSlug/attendance/monthly'
      path: '/attendance/monthly'
      fullPath: '/$clinicSlug/attendance/monthly'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceMonthlyRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/attendance/overtime': {
      id: '/_authenticated/$clinicSlug/attendance/overtime'
      path: '/attendance/overtime'
      fullPath: '/$clinicSlug/attendance/overtime'
      preLoaderRoute: typeof AuthenticatedClinicSlugAttendanceOvertimeRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/biometric/devices': {
      id: '/_authenticated/$clinicSlug/biometric/devices'
      path: '/biometric/devices'
      fullPath: '/$clinicSlug/biometric/devices'
      preLoaderRoute: typeof AuthenticatedClinicSlugBiometricDevicesRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/doctor/dashboard': {
      id: '/_authenticated/$clinicSlug/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/$clinicSlug/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicSlugDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/doctor/profile': {
      id: '/_authenticated/$clinicSlug/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/$clinicSlug/doctor/profile'
      preLoaderRoute: typeof AuthenticatedClinicSlugDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/doctor/schedule': {
      id: '/_authenticated/$clinicSlug/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/$clinicSlug/doctor/schedule'
      preLoaderRoute: typeof AuthenticatedClinicSlugDoctorScheduleRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/hr/assignments': {
      id: '/_authenticated/$clinicSlug/hr/assignments'
      path: '/hr/assignments'
      fullPath: '/$clinicSlug/hr/assignments'
      preLoaderRoute: typeof AuthenticatedClinicSlugHrAssignmentsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/hr/payroll': {
      id: '/_authenticated/$clinicSlug/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/$clinicSlug/hr/payroll'
      preLoaderRoute: typeof AuthenticatedClinicSlugHrPayrollRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/hr/salary': {
      id: '/_authenticated/$clinicSlug/hr/salary'
      path: '/hr/salary'
      fullPath: '/$clinicSlug/hr/salary'
      preLoaderRoute: typeof AuthenticatedClinicSlugHrSalaryRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/issues/my-reports': {
      id: '/_authenticated/$clinicSlug/issues/my-reports'
      path: '/issues/my-reports'
      fullPath: '/$clinicSlug/issues/my-reports'
      preLoaderRoute: typeof AuthenticatedClinicSlugIssuesMyReportsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/issues/report': {
      id: '/_authenticated/$clinicSlug/issues/report'
      path: '/issues/report'
      fullPath: '/$clinicSlug/issues/report'
      preLoaderRoute: typeof AuthenticatedClinicSlugIssuesReportRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/patient/profile': {
      id: '/_authenticated/$clinicSlug/patient/profile'
      path: '/patient/profile'
      fullPath: '/$clinicSlug/patient/profile'
      preLoaderRoute: typeof AuthenticatedClinicSlugPatientProfileRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/reports/appointments': {
      id: '/_authenticated/$clinicSlug/reports/appointments'
      path: '/reports/appointments'
      fullPath: '/$clinicSlug/reports/appointments'
      preLoaderRoute: typeof AuthenticatedClinicSlugReportsAppointmentsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/reports/attendance': {
      id: '/_authenticated/$clinicSlug/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/$clinicSlug/reports/attendance'
      preLoaderRoute: typeof AuthenticatedClinicSlugReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/reports/export': {
      id: '/_authenticated/$clinicSlug/reports/export'
      path: '/reports/export'
      fullPath: '/$clinicSlug/reports/export'
      preLoaderRoute: typeof AuthenticatedClinicSlugReportsExportRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/staff/profiles': {
      id: '/_authenticated/$clinicSlug/staff/profiles'
      path: '/staff/profiles'
      fullPath: '/$clinicSlug/staff/profiles'
      preLoaderRoute: typeof AuthenticatedClinicSlugStaffProfilesRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/agent': {
      id: '/_authenticated/$clinicSlug/system/agent'
      path: '/system/agent'
      fullPath: '/$clinicSlug/system/agent'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemAgentRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/audit-logs': {
      id: '/_authenticated/$clinicSlug/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/$clinicSlug/system/audit-logs'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemAuditLogsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/clinic-profile': {
      id: '/_authenticated/$clinicSlug/system/clinic-profile'
      path: '/system/clinic-profile'
      fullPath: '/$clinicSlug/system/clinic-profile'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemClinicProfileRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/devices': {
      id: '/_authenticated/$clinicSlug/system/devices'
      path: '/system/devices'
      fullPath: '/$clinicSlug/system/devices'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemDevicesRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/guide': {
      id: '/_authenticated/$clinicSlug/system/guide'
      path: '/system/guide'
      fullPath: '/$clinicSlug/system/guide'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemGuideRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/settings': {
      id: '/_authenticated/$clinicSlug/system/settings'
      path: '/system/settings'
      fullPath: '/$clinicSlug/system/settings'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/sync': {
      id: '/_authenticated/$clinicSlug/system/sync'
      path: '/system/sync'
      fullPath: '/$clinicSlug/system/sync'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemSyncRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/_authenticated/$clinicSlug/system/users': {
      id: '/_authenticated/$clinicSlug/system/users'
      path: '/system/users'
      fullPath: '/$clinicSlug/system/users'
      preLoaderRoute: typeof AuthenticatedClinicSlugSystemUsersRouteImport
      parentRoute: typeof AuthenticatedClinicSlugRouteRoute
    }
    '/api/public/device/events': {
      id: '/api/public/device/events'
      path: '/api/public/device/events'
      fullPath: '/api/public/device/events'
      preLoaderRoute: typeof ApiPublicDeviceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClinicSlugAppointmentsRouteChildren {
  AuthenticatedClinicSlugAppointmentsBookingRoute: typeof AuthenticatedClinicSlugAppointmentsBookingRoute
  AuthenticatedClinicSlugAppointmentsCalendarRoute: typeof AuthenticatedClinicSlugAppointmentsCalendarRoute
}

const AuthenticatedClinicSlugAppointmentsRouteChildren: AuthenticatedClinicSlugAppointmentsRouteChildren =
  {
    AuthenticatedClinicSlugAppointmentsBookingRoute:
      AuthenticatedClinicSlugAppointmentsBookingRoute,
    AuthenticatedClinicSlugAppointmentsCalendarRoute:
      AuthenticatedClinicSlugAppointmentsCalendarRoute,
  }

const AuthenticatedClinicSlugAppointmentsRouteWithChildren =
  AuthenticatedClinicSlugAppointmentsRoute._addFileChildren(
    AuthenticatedClinicSlugAppointmentsRouteChildren,
  )

interface AuthenticatedClinicSlugRouteRouteChildren {
  AuthenticatedClinicSlugAppointmentsRoute: typeof AuthenticatedClinicSlugAppointmentsRouteWithChildren
  AuthenticatedClinicSlugDashboardRoute: typeof AuthenticatedClinicSlugDashboardRoute
  AuthenticatedClinicSlugDepartmentsRoute: typeof AuthenticatedClinicSlugDepartmentsRoute
  AuthenticatedClinicSlugEmployeesRoute: typeof AuthenticatedClinicSlugEmployeesRoute
  AuthenticatedClinicSlugPatientsRoute: typeof AuthenticatedClinicSlugPatientsRoute
  AuthenticatedClinicSlugPositionsRoute: typeof AuthenticatedClinicSlugPositionsRoute
  AuthenticatedClinicSlugRoomsRoute: typeof AuthenticatedClinicSlugRoomsRoute
  AuthenticatedClinicSlugShiftsRoute: typeof AuthenticatedClinicSlugShiftsRoute
  AuthenticatedClinicSlugAdminDashboardRoute: typeof AuthenticatedClinicSlugAdminDashboardRoute
  AuthenticatedClinicSlugAdminIssuesRoute: typeof AuthenticatedClinicSlugAdminIssuesRoute
  AuthenticatedClinicSlugAttendanceAdjustmentsRoute: typeof AuthenticatedClinicSlugAttendanceAdjustmentsRoute
  AuthenticatedClinicSlugAttendanceCheckinRoute: typeof AuthenticatedClinicSlugAttendanceCheckinRoute
  AuthenticatedClinicSlugAttendanceDailyRoute: typeof AuthenticatedClinicSlugAttendanceDailyRoute
  AuthenticatedClinicSlugAttendanceLogsRoute: typeof AuthenticatedClinicSlugAttendanceLogsRoute
  AuthenticatedClinicSlugAttendanceManualRoute: typeof AuthenticatedClinicSlugAttendanceManualRoute
  AuthenticatedClinicSlugAttendanceMonthlyRoute: typeof AuthenticatedClinicSlugAttendanceMonthlyRoute
  AuthenticatedClinicSlugAttendanceOvertimeRoute: typeof AuthenticatedClinicSlugAttendanceOvertimeRoute
  AuthenticatedClinicSlugBiometricDevicesRoute: typeof AuthenticatedClinicSlugBiometricDevicesRoute
  AuthenticatedClinicSlugDoctorDashboardRoute: typeof AuthenticatedClinicSlugDoctorDashboardRoute
  AuthenticatedClinicSlugDoctorProfileRoute: typeof AuthenticatedClinicSlugDoctorProfileRoute
  AuthenticatedClinicSlugDoctorScheduleRoute: typeof AuthenticatedClinicSlugDoctorScheduleRoute
  AuthenticatedClinicSlugHrAssignmentsRoute: typeof AuthenticatedClinicSlugHrAssignmentsRoute
  AuthenticatedClinicSlugHrPayrollRoute: typeof AuthenticatedClinicSlugHrPayrollRoute
  AuthenticatedClinicSlugHrSalaryRoute: typeof AuthenticatedClinicSlugHrSalaryRoute
  AuthenticatedClinicSlugIssuesMyReportsRoute: typeof AuthenticatedClinicSlugIssuesMyReportsRoute
  AuthenticatedClinicSlugIssuesReportRoute: typeof AuthenticatedClinicSlugIssuesReportRoute
  AuthenticatedClinicSlugPatientProfileRoute: typeof AuthenticatedClinicSlugPatientProfileRoute
  AuthenticatedClinicSlugReportsAppointmentsRoute: typeof AuthenticatedClinicSlugReportsAppointmentsRoute
  AuthenticatedClinicSlugReportsAttendanceRoute: typeof AuthenticatedClinicSlugReportsAttendanceRoute
  AuthenticatedClinicSlugReportsExportRoute: typeof AuthenticatedClinicSlugReportsExportRoute
  AuthenticatedClinicSlugStaffProfilesRoute: typeof AuthenticatedClinicSlugStaffProfilesRoute
  AuthenticatedClinicSlugSystemAgentRoute: typeof AuthenticatedClinicSlugSystemAgentRoute
  AuthenticatedClinicSlugSystemAuditLogsRoute: typeof AuthenticatedClinicSlugSystemAuditLogsRoute
  AuthenticatedClinicSlugSystemClinicProfileRoute: typeof AuthenticatedClinicSlugSystemClinicProfileRoute
  AuthenticatedClinicSlugSystemDevicesRoute: typeof AuthenticatedClinicSlugSystemDevicesRoute
  AuthenticatedClinicSlugSystemGuideRoute: typeof AuthenticatedClinicSlugSystemGuideRoute
  AuthenticatedClinicSlugSystemSettingsRoute: typeof AuthenticatedClinicSlugSystemSettingsRoute
  AuthenticatedClinicSlugSystemSyncRoute: typeof AuthenticatedClinicSlugSystemSyncRoute
  AuthenticatedClinicSlugSystemUsersRoute: typeof AuthenticatedClinicSlugSystemUsersRoute
}

const AuthenticatedClinicSlugRouteRouteChildren: AuthenticatedClinicSlugRouteRouteChildren =
  {
    AuthenticatedClinicSlugAppointmentsRoute:
      AuthenticatedClinicSlugAppointmentsRouteWithChildren,
    AuthenticatedClinicSlugDashboardRoute:
      AuthenticatedClinicSlugDashboardRoute,
    AuthenticatedClinicSlugDepartmentsRoute:
      AuthenticatedClinicSlugDepartmentsRoute,
    AuthenticatedClinicSlugEmployeesRoute:
      AuthenticatedClinicSlugEmployeesRoute,
    AuthenticatedClinicSlugPatientsRoute: AuthenticatedClinicSlugPatientsRoute,
    AuthenticatedClinicSlugPositionsRoute:
      AuthenticatedClinicSlugPositionsRoute,
    AuthenticatedClinicSlugRoomsRoute: AuthenticatedClinicSlugRoomsRoute,
    AuthenticatedClinicSlugShiftsRoute: AuthenticatedClinicSlugShiftsRoute,
    AuthenticatedClinicSlugAdminDashboardRoute:
      AuthenticatedClinicSlugAdminDashboardRoute,
    AuthenticatedClinicSlugAdminIssuesRoute:
      AuthenticatedClinicSlugAdminIssuesRoute,
    AuthenticatedClinicSlugAttendanceAdjustmentsRoute:
      AuthenticatedClinicSlugAttendanceAdjustmentsRoute,
    AuthenticatedClinicSlugAttendanceCheckinRoute:
      AuthenticatedClinicSlugAttendanceCheckinRoute,
    AuthenticatedClinicSlugAttendanceDailyRoute:
      AuthenticatedClinicSlugAttendanceDailyRoute,
    AuthenticatedClinicSlugAttendanceLogsRoute:
      AuthenticatedClinicSlugAttendanceLogsRoute,
    AuthenticatedClinicSlugAttendanceManualRoute:
      AuthenticatedClinicSlugAttendanceManualRoute,
    AuthenticatedClinicSlugAttendanceMonthlyRoute:
      AuthenticatedClinicSlugAttendanceMonthlyRoute,
    AuthenticatedClinicSlugAttendanceOvertimeRoute:
      AuthenticatedClinicSlugAttendanceOvertimeRoute,
    AuthenticatedClinicSlugBiometricDevicesRoute:
      AuthenticatedClinicSlugBiometricDevicesRoute,
    AuthenticatedClinicSlugDoctorDashboardRoute:
      AuthenticatedClinicSlugDoctorDashboardRoute,
    AuthenticatedClinicSlugDoctorProfileRoute:
      AuthenticatedClinicSlugDoctorProfileRoute,
    AuthenticatedClinicSlugDoctorScheduleRoute:
      AuthenticatedClinicSlugDoctorScheduleRoute,
    AuthenticatedClinicSlugHrAssignmentsRoute:
      AuthenticatedClinicSlugHrAssignmentsRoute,
    AuthenticatedClinicSlugHrPayrollRoute:
      AuthenticatedClinicSlugHrPayrollRoute,
    AuthenticatedClinicSlugHrSalaryRoute: AuthenticatedClinicSlugHrSalaryRoute,
    AuthenticatedClinicSlugIssuesMyReportsRoute:
      AuthenticatedClinicSlugIssuesMyReportsRoute,
    AuthenticatedClinicSlugIssuesReportRoute:
      AuthenticatedClinicSlugIssuesReportRoute,
    AuthenticatedClinicSlugPatientProfileRoute:
      AuthenticatedClinicSlugPatientProfileRoute,
    AuthenticatedClinicSlugReportsAppointmentsRoute:
      AuthenticatedClinicSlugReportsAppointmentsRoute,
    AuthenticatedClinicSlugReportsAttendanceRoute:
      AuthenticatedClinicSlugReportsAttendanceRoute,
    AuthenticatedClinicSlugReportsExportRoute:
      AuthenticatedClinicSlugReportsExportRoute,
    AuthenticatedClinicSlugStaffProfilesRoute:
      AuthenticatedClinicSlugStaffProfilesRoute,
    AuthenticatedClinicSlugSystemAgentRoute:
      AuthenticatedClinicSlugSystemAgentRoute,
    AuthenticatedClinicSlugSystemAuditLogsRoute:
      AuthenticatedClinicSlugSystemAuditLogsRoute,
    AuthenticatedClinicSlugSystemClinicProfileRoute:
      AuthenticatedClinicSlugSystemClinicProfileRoute,
    AuthenticatedClinicSlugSystemDevicesRoute:
      AuthenticatedClinicSlugSystemDevicesRoute,
    AuthenticatedClinicSlugSystemGuideRoute:
      AuthenticatedClinicSlugSystemGuideRoute,
    AuthenticatedClinicSlugSystemSettingsRoute:
      AuthenticatedClinicSlugSystemSettingsRoute,
    AuthenticatedClinicSlugSystemSyncRoute:
      AuthenticatedClinicSlugSystemSyncRoute,
    AuthenticatedClinicSlugSystemUsersRoute:
      AuthenticatedClinicSlugSystemUsersRoute,
  }

const AuthenticatedClinicSlugRouteRouteWithChildren =
  AuthenticatedClinicSlugRouteRoute._addFileChildren(
    AuthenticatedClinicSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClinicSlugRouteRoute: typeof AuthenticatedClinicSlugRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClinicSlugRouteRoute:
    AuthenticatedClinicSlugRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDeviceEventsRoute: ApiPublicDeviceEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
